export default [
  {
    id: '1000000',
    topic: 'TESTING',
    resultsImg: '/images/sauerbraten-2512443_640.jpg',
    resultsImgAlt: 'TESTING TESTING BLAH BLAHBLAH',
    questions: [
      {
        id: 'testq1',
        question: 'Am I the first question?',
        answers: [
          'Yes, you are.',
          'Snotwaffles',
          'Hey diddly ho there',
          "New York New York. It's a beautiful town.",
          "The Bronx is up, and the Battery's down",
        ],
      },
      {
        id: 'testq2',
        question: 'Am I the second question?',
        answers: [
          'I do believe you are, you dickens.',
          'Beetlejuice! Beetlejuice! Beetlejuice!',
          "You're gonna need a bigger boat.",
          "I'll have what she's having.",
          'My name is Inego Montoya. You killed my father. Prepare to die.',
        ],
      },
      {
        id: 'testq3',
        question: 'Am I the third question?',
        answers: [
          'Aye, you are the turd, laddie.',
          'Cats and fish tails',
          'Dogs and bacon',
          'Ducks and green peas',
          'Elephants and peanuts',
        ],
      },
      {
        id: 'testq4',
        question: 'Am I the fourth question?',
        answers: [
          'The fourth is strong with this one',
          'Darthie',
          'Jabbie',
          'Bobafettie',
          'Sithie',
        ],
      },
      {
        id: 'testq5',
        question: 'Am I the fifth question?',
        answers: [
          'five, fünf, cinq, cinco, fem, cinque',
          'chocolate cake',
          'blueberry crumble',
          'raspberry-filled donuts',
          'soufflé',
        ],
      },
      {
        id: 'testq6',
        question: 'Am I the sixth question?',
        answers: [
          'I am the square root of 36',
          'How Soon Is Now',
          'This Charming Man',
          'Girlfriend in a Coma',
          'Unhappy birthday',
        ],
      },
    ],
  },
  {
    id: '1',
    topic: 'German capital cities',
    resultsImg: '/images/map-304071_1280.png',
    resultsImgAlt: "Map of Germany showing the states' borders",
    questions: [
      {
        id: 't1q1',
        question: 'Baden-Württemberg',
        answers: [
          'Stuttgart',
          'Baden-Württemberg is a city-state and its own capital.',
          'Ulm',
          'Heidelberg',
          'Badenschmaden',
        ],
        image: '/images/stuttgart.png',
        imageAlt: 'Wuerttemberg Mausoleum with a vineyard in the foreground',
      },
      {
        id: 't1q2',
        question: 'Bavaria (Bayern)',
        answers: [
          'Munich (München)',
          'Augsberg',
          'Ingolstadt',
          'Regensburg',
          'Oberammergau-Unterammergau',
        ],
        image: '/images/munich.png',
        imageAlt: 'Marienplatz with the New City Hall (Neues Rathaus)',
      },
      {
        id: 't1q3',
        question: 'Berlin',
        answers: [
          'Berlin is a city-state and is its own capital',
          'Berlinstadt',
          'Ost-West-Berlinerhaven',
          'Berlinnenstadt',
          'Bärland',
        ],
        image: '/images/berlin.png',
        imageAlt:
          'Drone view of the Spree River, Museum Island, and Berlin Palace',
      },
      {
        id: 't1q4',
        question: 'Brandenburg',
        answers: [
          'Potsdam',
          'Brandenburg is a city-state and its own capital',
          'Oranienburg',
          'Petershagen-Eggersdorf',
          'Parisdorf',
        ],
        image: '/images/potsdam.png',
        imageAlt:
          'view of old city hall with the statue of Fortuna auf dem Fortunaportal in the foreground',
      },
      {
        id: 't1q5',
        question: 'Bremen',
        answers: [
          'Bremen is a city-state and its own capital',
          'Havenbremer',
          'Bremänner',
          'Schildkröte',
          'Bremen is not a German city, lost in a poker game against Liechtenstein',
        ],
        image: '/images/bremen.png',
        imageAlt: 'Bremen market place (Marktplatz)',
      },
      {
        id: 't1q6',
        question: 'Hamburg',
        answers: [
          'Hamburg is a city-state and its own capital',
          'Inner Alster',
          'Elbe',
          'Wandsbek',
          'Rote Grützendorf',
        ],
        image: '/images/hamburg.png',
        imageAlt: "St Pauli's pier and the head of the Elbe River",
      },
      {
        id: 't1q7',
        question: 'Hesse (Hessen)',
        answers: [
          'Wiesbaden',
          'Darmstadt',
          'Kassel',
          'Frankfurt',
          'Kaiserschmarren',
        ],
        image: '/images/wiesbaden.png',
        imageAlt: 'Kurhaus Wiesbaden',
      },
      {
        id: 't1q8',
        question: 'Lower Saxony (Niedersachsen)',
        answers: [
          'Hanover (Hannover)',
          'Göttingen',
          'Wolfsburg',
          'Lüneburg',
          'Goetheburg',
        ],
        image: '/images/hannover.png',
        imageAlt:
          'View over city center including the old town hall and St Georgii et Jacobi church',
      },
      {
        id: 't1q9',
        question: 'Mecklenburg-Vorpommern',
        answers: [
          'Schwerin',
          'Stralsund',
          'Greifswald',
          'Wismar',
          'Vierpommes',
        ],
        image: '/images/schwerin.png',
        imageAlt: 'View of the orangerie and the Lake Schwerin',
      },
      {
        id: 't1q10',
        question: 'Rhineland-Palatinate (Rheinland-Pfalz)',
        answers: [
          'Mainz',
          'Ludwigshafen am Rhein',
          'Trier',
          'Koblenz',
          'Pfalzundseffer',
        ],
        image: '/images/mainz.png',
        imageAlt: 'View over Mainz and the Rhine',
      },
      {
        id: 't1q11',
        question: 'North Rhine-Westphalia (Nordrhein-Westfalen)',
        answers: [
          'Düsseldorf',
          'Dortmund',
          'Essen',
          'Bielefeld',
          'Rheinischer-Sauerbraten',
        ],
        image: '/images/duesseldorf.png',
        imageAlt: "Frank Owen Gehry's New Zollhof buildings in Media Harbour",
      },
      {
        id: 't1q12',
        question: 'Saarland',
        answers: [
          'Saarbrücken',
          'Neunkirchen',
          'Homburg',
          'Völkingen',
          'Zehnschulen',
        ],
        image: '/images/saarbrucken.png',
        imageAlt: 'The Baroque Louis Church (Ludwigskirche)',
      },
      {
        id: 't1q13',
        question: 'Saxony (Sachsen)',
        answers: ['Dresden', 'Chemnitz', 'Zwickau', 'Görlitz', 'Raupenkot'],
        image: '/images/dresden.png',
        imageAlt:
          'Dresden Cathedral (Kathedrale Sanctissimae Trinitatis in the inner old city',
      },
      {
        id: 't1q14',
        question: 'Saxony-Anhalt (Sachsen-Anhalt)',
        answers: [
          'Magdeburg',
          'Halle (Saale)',
          'Dressau-Roßlau',
          'Wittenburg',
          'Bahn-Wahn',
        ],
        image: '/images/magdeburg.png',
        imageAlt:
          'View over the city with the City Park (Stadtpark) and the Wheel of Hope ferris wheel in the foreground',
      },
      {
        id: 't1q15',
        question: 'Schleswig-Holstein',
        answers: [
          'Kiel',
          'Lübeck',
          'Flensburg',
          'Neumünster',
          'Meerschweinchen-Holzbeinchen',
        ],
        image: '/images/kiel.png',
        imageAlt:
          'View of the opera house and city hall from the opposite end of Lake Little Kiel',
      },
      {
        id: 't1q16',
        question: 'Thuringia (Thüringen)',
        answers: [
          'Erfurt',
          'Gera',
          'Ilmenau',
          'Jena',
          'Kickelhahn-Holzbeinchen am Humbach',
        ],
        image: '/images/erfuhrt.png',
        imageAlt:
          "Old Erfurt and the view from the tower of St. Giles' Church over the houses standing on the Krämerbrücke bridge",
      },
    ],
  },
  {
    id: '2',
    topic: 'German food and drink',
    resultsImg: '/images/sauerbraten-2512443_640.jpg',
    resultsImgAlt: 'Plate of sauerbraten and spaetzle',
    questions: [
      {
        id: 't2q1',
        question: 'What is Spätzle?',
        answers: [
          'An egg noodle or dumpling',
          'A cocktail of cola and sparkling apple juice',
          'A berry found around south eastern German',
          'What Bavarians shout when dinner is ready',
          'The small sprinkles on a cake or ice cream',
        ],
      },
      {
        id: 't2q2',
        question: 'What part of Germany produces the most wine?',
        answers: [
          'Rheinhessen',
          'Pfalz (Palatinate)',
          'Baden',
          'Mosel',
          'Rieslingia',
        ],
      },
      {
        id: 't2q3',
        question: 'What is "Leberkäse?',
        answers: [
          'A pork, bacon, and spices meatloaf',
          'A liver, cheese, and mustard sandwich',
          "Liver sausage encased in goat's intestines",
          'The job of making cheese: labor + cheese',
          'A meat pudding made with liver and cream cheese',
        ],
      },
      {
        id: 't2q4',
        question: 'What is "Rollmops"?',
        answers: [
          'A pickled herring rolled around a gherkin and onion',
          'Something Germans shout before cutting into a cake for good luck',
          'A pastry similar to cannoli',
          'The oldest restaurant in Rudolstadt',
          'A kitchen tool used to make special Christmas cookies',
        ],
      },
      {
        id: 't2q5',
        question:
          'What is a dessert that also means "Oh, rubbish" or "Oh, nonsense"?',
        answers: [
          'Ach, Schmarrn!',
          'Ach, du Leberwurstchen!',
          'Ach, Scheisswälder!',
          'Ach, roter Schmutz',
          'Ach, Verdammntnudeln',
        ],
      },
      {
        id: 't2q6',
        question:
          'What is the colloquial term for Maultaschen ("Little meat bags")?',
        answers: [
          "Herrgottsb'scheisserle (little God-cheaters)",
          'Damenbrüstchen (little lady tatas)',
          'Sündentaschen (sin pockets)',
          'Troll-Ärsche (troll asses)',
          'heiße Kreuznonnen (hot cross nuns)',
        ],
      },
      {
        id: 't2q7',
        question: 'What is "Kölsch"?',
        answers: [
          'A style of beer that orginated from Cologne',
          'A Bavarian meat pastry',
          'The German equivalent to "achoo!"',
          'Slang for beer farts',
          'A popular cream and vanilla sauce Germans add to desserts',
        ],
      },
      {
        id: 't2q8',
        question: 'What do the US midwesterners call "Quark"?',
        answers: [
          'Farmer cheese',
          'Cheese à la pie',
          'Duck cheese',
          'Dumpling sauce',
          'Particle cheese',
        ],
      },
      {
        id: 't2q9',
        question:
          'Verein Gegen Betrügerischen Einshenken protects you against what?',
        answers: [
          'Not getting enough beer in a pour at a festival',
          'Getting flat beer',
          'Getting a dirty Bierstein',
          'Vermin bites at restaurants',
          'Ach, Verdammntnudeln',
        ],
      },
      {
        id: 't2q10',
        question: 'What is a "Radler"?',
        answers: [
          'Lager and lemon soda',
          'A beer or wine bike delivery service',
          'The drink German and Austrian moms give their babies (like a formula)',
          'An insult among chefs to refer to the worst cook',
          'Slang for a person too cheap to buy a round of drinks',
        ],
      },
      {
        id: 't2q11',
        question: 'What does "Feierabend" mean?',
        answers: [
          'End-of-work celebration (akin to Happy Hour)',
          'The pagan ritual of sharing stories around a fire (Campfire)',
          'It is similar to "Prost!" but said only amongst women',
          "The part for an employee's last day of work when they retire",
          'What the bartender shouts (like "Last call!")',
        ],
      },
      {
        id: 't2q12',
        question: 'What are "Himbeere", "Stachelbeere", and "Johannisbeere"?',
        answers: [
          'Raspberry, gooseberry, and red current',
          'The names of the 3 bears in Goldilocks',
          'The 3 most popular beers sold in Bavaria',
          'The 3 worst teams in the German football league',
          '3 terms for Berkbällchen (Rocky Mountain oysters)',
        ],
      },
      {
        id: 't2q13',
        question: 'What is "Mostertpöttche"?',
        answers: [
          'The famous pot Düsseldorf mustard comes in',
          'Slang for a pot belly',
          'The title of a still life of German food by Mario Barthus',
          'The sausage Munster is known for',
          'The German name for Cinderella',
        ],
      },
    ],
  },
  {
    id: '3',
    topic: 'German long and unique words',
    resultsImg: '/images/Long-German-word-Fussbodenschleifmaschinenverleih.jpg',
    resultsImgAlt: 'view of Fussbodenschleifmaschinenverleih store front and sign',
    questions: [
      {
        id: 't3q1',
        question: 'What does "Haarmonie" mean?',
        answers: [
          'Reassuring your hairdresser',
          'Singing off key at church',
          'When your hair\'s color blends perfectly',
          'A rabbit warren',
          'The pleasant smell from shampoo',
        ],
      },
      {
        id: 't3q2',
        question: 'If you have "Schmutzigeshaarbedauern", what should you have done?',
        answers: [
          'Not gone that extra day without washing your hair',
          'Had less dessert',
          'Studied harder for midterms',
          'Cleaned your pots and pans before going to bed',
          'Not have had that last beer',
        ],
      },
      {
        id: 't3q3',
        question: 'What could cause "Ruiniertnägelniedergeschlagenheit"?',
        answers: [
          'Seeing that your freshly manicured toes are smudged',
          'Excessive exercise',
          'Shaving your legs with a rusty razor',
          'Rabies',
          'Dropping your things just before exiting an elevator',
        ],
      },
      {
        id: 't3q4',
        question: 'What led to "Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz"?',
        answers: [
          'The 1990s mad cow disease crisis',
          'The spike in teen crime after the Berlin Wall fell',
          'King Ludwig\'s law to criminalize dancing on Sundays',
          'The 30 Years War',
          'Crystal meth in the monasteries',
        ],
      },
      {
        id: 't3q5',
        question: 'Why is a "Schwiegermutterkurve" dangerous?',
        answers: [
          'It\'s a dangerous hair-pin or blind curve on a road',
          'It\'s socially unacceptable to stare at your stepmother\'s curve',
          'It causes blockages in the arteries',
          'It causes spontaneous combustion in rodents',
          'It is a poison that smells like chocolate',
        ],
      },
      {
        id: 't3q6',
        question: '"Honigkuchenpferd" is a cookie, but it is also ... what?',
        answers: [
          'A smug or proud grin',
          'The winning horse in dressage competition',
          'The term for a baby hippopotamus',
          'The colloquial term for a nurse',
          'The queen bee in a colony',
        ],
      },
      {
        id: 't3q7',
        question: 'What is a "Streichholzschächtelchen"?',
        answers: [
          'A matchbox',
          'A small fight or spat',
          'A wooden marionette',
          'A paint brush',
          'A small bag used to carry schoolbooks',
        ],
      },
      {
        id: 't3q8',
        question: 'What is a "Weichei" and what does it describe?',
        answers: [
          'A soft egg / a coward',
          'A small dog / a tedious individual',
          'Soggy toast / a sick individual',
          'Whites of the eye / a strict teacher',
          'A white sausage / a gym rat',
        ],
      },
      {
        id: 't3q9',
        question: 'What is "Kummerspeck"?',
        answers: [
          'Emotional eating (worry bacon)',
          'A cummberbund (crumbs + band)',
          'Markings on a window from a dog\'s nose (moist nose)',
          'A savory pastry from Aachen',
          'A muskrat',
        ],
      },
      {
        id: 't3q10',
        question: 'What does "Erbsenzähler" mean?',
        answers: [
          'A nitpicker (pea counter)',
          'A cashier at a farmers market (peas seller)',
          'A stray dog (earth scrabbler)',
          'The lower intestines (long food train)',
          'The socks Bavarian men wear with Lederhosen',
        ],
      },
      {
        id: 't3q11',
        question: 'What do you want to do when you see someone with a "Backpfeifengesicht"?',
        answers: [
          'Slap them (slappable face)',
          'Kiss them (smoochable lips)',
          'Cry for jealousy (high end jewels)',
          'Help them cross the street (can\'t see from puffy eyelids)',
          'Carry it for them (back-breaking luggage)',
        ],
      },
      {
        id: 't3q12',
        question: 'What is happening to someone with "Geheimratsecken"?',
        answers: [
          'They\'re losing their hair (privy councillor\'s corners)',
          'They have poison ivy (secret scratching)',
          'They are being reassigned to another job due to complaints (gossip sacks)',
          'They are getting a divorce (home ratsack)',
          'They have chicken pox (itchy freckles)',
        ],
      },
    ],
  },
  {
    id: '4',
    topic: 'German arts and literature',
    resultsImg: '/images/beethoven-8803301_1280.jpg',
    resultsImgAlt: 'Beethoven sitting at a desk composing at candlelight',
    questions: [
      {
        id: 't4q1',
        question: 'What was the German literature movement and music that occurred between the late 1760s and early 1780s called?',
        answers: [
          'Sturm und Drang',
          'Schiller und Miller',
          'Schimpf und Drama',
          'Blut und Natur',
          'Peinlichfressen',
        ],
      },
      {
        id: 't4q2',
        question: 'Where was Goethe born?',
        answers: [
          'Frankfurt am Main',
          'Frankfurt an der Oder',
          'Frankfurt ob der Aber',
          'Frankfurt beim Deshalb',
          'Frankfurt under Ober',
        ],
      },
    ],
  },
];
